server:
  context-path: /item
  port: 8082

db-groups:
  - list:
      - host: localhost
        port: 3306
        name: test
        user: root
        password: 123456
        mappers:
          - com.bjtu.item.db.mapper
  - name: master
    list:
      - host: localhost
        port: 3306
        name: test
        user: root
        password: 123456
        mappers:
          - com.bjtu.item.db.mapper

thymeleaf:
    prefix: classpath:/static/